@startuml
digraph facts {

richard3_needsHelp [label ="richard3_needsHelp
Needs your help. His Fathers death was somewhat suspicious"]
george4_diedMysteriously [label ="george4_diedMysteriously
died under mysterious circumstances"]
george4_weirdSymptoms [label ="george4_weirdSymptoms
had weird symptoms shortly before his death"]
george4_wasPoisoned [label ="george4_wasPoisoned
was probably poisoned to death"]
severin_behavesWeirdly [label ="severin_behavesWeirdly
did not quite like to investigate the death of King George IV further"]

richard3_needsHelp -> george4_weirdSymptoms
george4_diedMysteriously -> george4_weirdSymptoms
george4_weirdSymptoms -> george4_wasPoisoned
george4_wasPoisoned -> severin_behavesWeirdly

}
@enduml